name: EvergladesTools
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - bioconda::snakemake
  - conda-forge::python>=3.9
  - dask
  - distributed
  - geopandas
  - nvidia::cudatoolkit=11.3
  - pandas
  - pip
  - pytest
  - pytorch
  - pytorch::pytorch
  - pytorch::torchvision
  - shapely
  - torchvision
  - pip:
    - comet_ml
    - dask_jobqueue
    - deepforest
    - geopandas
    - mapboxcli
    - opencv-python
    - pandas
    - Panoptes
    - panoptes_client
    - panoptescli
    - paramiko
    - pytest
    - PyYAML
    - rasterio
    - rio-mbtiles
    - shapely
    - slidingwindow
    - xmltodict
